version: "3.8"

services:
  # Integration tests
  integration-tests:
    build:
      context: ..
      dockerfile: build/Dockerfile.integration
    container_name: calendar-integration-tests
    depends_on:
      calendar:
        condition: service_started
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - calendar-network
    environment:
      - CGO_ENABLED=0

networks:
  calendar-network:
    external: true
