logger:
  level: "info"

storage:
  type: "sql"
  dsn: "postgres://user:password@localhost:6432/calendar?sslmode=disable"

kafka:
  brokers:
    - "localhost:9092"
  topic: "calendar-notifications"
  max_attempts: 5
  retry_backoff: 5s